/*
**
** Copyright (C) 2013 Telechips Inc.
** Copyright 2008, The Android Open Source Project
**
** Licensed under the Apache License, Version 2.0 (the "License");
** you may not use this file except in compliance with the License.
** You may obtain a copy of the License at
**
**     http://www.apache.org/licenses/LICENSE-2.0
**
** Unless required by applicable law or agreed to in writing, software
** distributed under the License is distributed on an "AS IS" BASIS,
** WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
** See the License for the specific language governing permissions and
** limitations under the License.
*/

#ifndef ANDROID_IPCMSERVICENOTIFY_H
#define ANDROID_IPCMSERVICENOTIFY_H

#include <utils/RefBase.h>
#include <binder/IInterface.h>
#include <binder/Parcel.h>

#define NOTIFY_CODE_SAMPLERATE 0xF0010
#define NOTIFY_CODE_DURATION 0xF0011
#define NOTIFY_CODE_MEDIA_TITLE 0xF0012
#define NOTIFY_CODE_MEDIA_ARTIST 0xF0013
#define NOTIFY_CODE_MEDIA_ABLUM_TITLE 0xF0014
#define NOTIFY_CODE_MEDIA_ABLUM_ARTIST 0xF0015
#define NOTIFY_CODE_MEDIA_PLAYBACK_POSITION 0xF0016
#define NOTIFY_CODE_MEDIA_PCM_DATA_RECEIVE 0xF0017
#define NOTIFY_CODE_MEDIA_PLAYBACK_STATUS 0xF0018
#define NOTIFY_CODE_MEDIA_PLAYBACK_QUEUE_INDEX 0xF0019
#define NOTIFY_CODE_MEDIA_PLAYBACK_QUEUE_COUNT 0xF001A
#define NOTIFY_CODE_MEDIA_PLAYBACK_QUEUE_CAPTER_INDEX 0xF001B
#define NOTIFY_CODE_MEDIA_PLAYBACK_SHUFFLE_MODE 0xF001C
#define NOTIFY_CODE_MEDIA_PLAYBACK_REPEAT_MODE 0xF001D
#define NOTIFY_CODE_MEDIA_PLAYBACK_APP_NAME 0xF001E
#define NOTIFY_CODE_PB_MEDIA_LIBRARY_UID 0xF0020
#define NOTIFY_CODE_PB_APPLE_MUSIC_RADIO_AD 0xF0021
#define NOTIFY_CODE_PB_APPLE_MUSIC_RADIO_STATION_NAME 0xF0022
#define NOTIFY_CODE_PB_APPLE_MUSIC_RADIO_STATION_PLAYLIST_ID 0xF0023
#define NOTIFY_CODE_MEDIA_PLAYBACK_SPEED 0xF0024
#define NOTIFY_CODE_SET_ELAPSED_TIME_AVAILABLE 0xF0025
#define NOTIFY_CODE_PLAY_BACK_QUEUELIST_AVAIL 0xF0026
#define NOTIFY_CODE_PLAY_BACK_QUEUELIST_TRANSFER_ID 0xF0027
#define NOTIFY_CODE_MEDIA_PLAYBACK_BUNDLE_ID 0xF0028
#define NOTIFY_CODE_PLAY_BACK_QUEUELIST_CONTENT_TRANSFER 0xF0029
#define NOTIFY_CODE_MEDIA_ITEM_PERSISTENT_ID 0xF002A
#define NOTIFY_CODE_MEDIA_ITEM_MEDIA_TYPE 0xF002B
#define NOTIFY_CODE_MEDIA_ITEM_MEDIA_RATING 0xF002C
#define NOTIFY_CODE_MEDIA_ITEM_ALBUM_PERSISTENT_ID 0xF002AD
#define NOTIFY_CODE_MEDIA_ITEM_ALBUM_TRACK_NUMBER 0xF002E
#define NOTIFY_CODE_MEDIA_ITEM_ALBUM_TRACK_COUNT 0xF002F
#define NOTIFY_CODE_MEDIA_ITEM_ALBUM_DISC_NUMBER 0xF0030
#define NOTIFY_CODE_MEDIA_ITEM_ALBUM_DISC_COUNT 0xF0031
#define NOTIFY_CODE_MEDIA_ITEM_ALBUM_ARTIST_PID 0xF0032
#define NOTIFY_CODE_MEDIA_ITEM_GENRE_PID 0xF0033
#define NOTIFY_CODE_MEDIA_GENRE 0xF0034
#define NOTIFY_CODE_MEDIA_ITEM_COMPOSER_PID 0xF0035
#define NOTIFY_CODE_MEDIA_COMPOSER 0xF0036
#define NOTIFY_CODE_MEDIA_ITEM_ISPARTOF_COMPILATION 0xF0037
#define NOTIFY_CODE_MEDIA_ITEM_IS_LIKE_SUPPORTED 0xF0038
#define NOTIFY_CODE_MEDIA_ITEM_IS_BEAN_SUPPORTED 0xF0039
#define NOTIFY_CODE_MEDIA_ITEM_IS_LIKED 0xF003A
#define NOTIFY_CODE_MEDIA_ITEM_IS_BANNED 0xF003B
#define NOTIFY_CODE_MEDIA_ITEM_IS_RESIDENT_ON_DEVICE 0xF003C
#define NOTIFY_CODE_MEDIA_ITEM_ART_WORK_FILE_TRANSFER_ID 0xF003D
#define NOTIFY_CODE_MEDIA_ITEM_CHAPTER_COUNT 0xF003E
#define NOTIFY_CODE_MEDIA_LIBRARY_NAME 0xF003F
#define NOTIFY_CODE_MEDIA_LIBRARY_UID 0xF0040
#define NOTIFY_CODE_MEDIA_LIBRARY_TYPE 0xF0041
#define NOTIFY_CODE_MEDIA_LIBRARY_UPDATE_UID 0xF0042
#define NOTIFY_CODE_MEDIA_LIBRARY_UPDATE_REVISION 0xF0043
#define NOTIFY_CODE_MEDIA_ITEM_DELETE_UPDATE_PID 0xF0044
#define NOTIFY_CODE_MEDIA_PLAY_LIST_DELETE_UPDATE_PID 0xF0045
#define NOTIFY_CODE_PLAY_ALL_SONGS_CAPABLE 0xF0046
#define NOTIFY_CODE_IS_HIDING_REMOTE_ITEMS 0xF0047
#define NOTIFY_CODE_MEDIA_LIBRARY_UPDATE_PROGRESS 0xF0048
#define NOTIFY_CODE_MEDIA_LIBRARY_RESET 0xF0049
#define NOTIFY_CODE_MEDIA_LIBRARY_UPDATE_PLAYLIST_PID 0xF004A
#define NOTIFY_CODE_MEDIA_LIBRARY_UPDATE_PLAYLIST_NAME 0xF004B
#define NOTIFY_CODE_MEDIA_LIBRARY_UPDATE_PARENT_PLAYLIST_PID 0xF004C
#define NOTIFY_CODE_MEDIA_UPDATE_PLAYLIST_IS_GENIUSMIX 0xF004D
#define NOTIFY_CODE_MEDIA_UPDATE_PLAYLIST_IS_FOLDER 0xF004E
#define NOTIFY_CODE_CONTAINED_MEDIA_ITEM_FS_ID 0xF0050
#define NOTIFY_CODE_MEDIA_UPDATE_PLAYLIST_IS_RADIO_STATION 0xF0051
#define NOTIFY_CODE_MEDIA_UPDATE_PLAYLIST_CONTENT_TRANSFER 0xF0052
#define NOTIFY_CODE_MEDIA_ITEM_ARTIST_PID 0xF0053
#define NOTIFY_CODE_MEDIA_NOW_PLAYING_ARTWORK_DATA_START 0xF0054
#define NOTIFY_CODE_MEDIA_NOW_PLAYING_ARTWORK_DATA_FINISH 0xF0055
#define NOTIFY_ON_MEDIA_LIBRARY_INFOMATION 0xF0056
#define NOTIFY_ON_MEDIA_LIBRARY_UPDATE 0xF0057
#define NOW_PLAYING_PB_QUEUE_CONTENTS_START 0xF0058
#define NOW_PLAYING_PB_QUEUE_CONTENTS_FINISH 0xF0059
#define MEDIA_LIBRARY_UPDATE_PLAYLIST_CONTENTS_START 0xF005A
#define MEDIA_LIBRARY_UPDATE_PLAYLIST_CONTENTS_FINISH 0xF005B
#define MEDIA_ITEM_NOW_PLAYING_PB_QUEUE_CONTENTS_START 0xF005C
#define MEDIA_ITEM_NOW_PLAYING_PB_QUEUE_CONTENTS_FINISH 0xf005d
#define MEDIA_ITEM_LIST_UPDATE_PLAYLIST_CONTENTS_START 0xf005e
#define MEDIA_ITEM_LIST_UPDATE_PLAYLIST_CONTENTS_FINISH 0xf005f
#define NOTIFY_CODE_IPOD_START_READY 0xf0060
#define NOTIFY_ON_NOW_PLAYING_MEDIA_ITEM_ATTRIBUTES 0xf0061
#define NOTIFY_ON_NOW_PLAYING_PLAYBACK_ATTRIBUTES 0xf0062

namespace android {

class IPcmServiceNotify: public IInterface
{
public:
    DECLARE_META_INTERFACE(PcmServiceNotify);

    virtual void notify(int msg, int ext1, int ext2,int ext3) = 0;
    virtual void notifyObj(int msg, int ext1, int ext2, const Parcel *obj) = 0;
	
	virtual void notifyRawString(int msg, int ext1, const unsigned char  *obj) = 0;
	virtual void notifyRawByte(int msg, int ext1, const unsigned char  *obj) = 0;
	virtual void notifyIap2FileTransfer(int msg, int fileName_len, const unsigned char * fileName,
									int playListPid_len,  const unsigned char  *playListPid,
									int libraryUID_len,const unsigned char  *libraryUID) = 0;
};

// ----------------------------------------------------------------------------

class BnPcmServiceNotify: public BnInterface<IPcmServiceNotify>
{
public:
    virtual status_t    onTransact( uint32_t code,
                                    const Parcel& data,
                                    Parcel* reply,
                                    uint32_t flags = 0);
};

}; // namespace android

#endif // ANDROID_IIAPSERVICENOTIFY_H
